### ISSUE TITLE
Sandbox endpoint return 500

### ISSUE THREAD

**Issue by 2pd** [splitpayments/api-documentation#31]
Operating system: ✍️  
``` bash
Mac

```
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️

```bash
commit cf29f6786c288b6111239b8e8b211f8ae2fbc4c3
```

Browser version(s): ✍️

```
Not used
```
Ruby version (run `ruby -v`):  ✍️ TODO
```
2.6.0
```

Environment:

``` 
Sandbox
 ```

---

The endpoint of 

```
POST {{api_host}}/contacts
```

return `500 Internal Server Error`
with payload

```
{
    "nickname": "jeremy",
    "metadata": {
        "custom_key": "Custom string",
        "another_custom_key": "Maybe a URL"
    }
}

```

I think ```jeremy``` nick name is not existing in the sandbox env.

**Comment by antulik** [comment]
@2pd Thank you for reporting this  ❤️ 

This issue is fixed now. 
Sorry for the delay, for a prompt reply you can contact us through online chat or at support@splitpayments.com.au
